name: catch_cow_app
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  modal_bottom_sheet: ^1.0.0+1
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  firebase_storage: ^5.1.0
  firebase_image: ^0.3.0
  path_provider: ^1.6.24
  image_picker: ^0.6.7+14
  http: ^0.12.2
  hexcolor: ^1.0.6
  flutter_slidable: ^0.5.7
  path: ^1.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/hol.png
    - images/Preloader_1.gif
    - images/Preloader_2.gif
    - images/Preloader_3.gif
    - images/Preloader_4.gif
    - images/Preloader_5.gif